<?php $billingInfo = $this->getCustomerInfo(); ?>

<div class="sepa-mandate-card" style="display: none;">
    <div class="sepa-card-header">
        <div class="sepa-card-header-text">
            <div class="sepa-card-title">
                <h3 style="font-weight: bold;">SEPA Direct Debit Mandate for single payment</h3>
            </div>
        </div>
    </div>
    <div class="sepa-mandate-content">
        <div class="sepa-creditor">
            <h2 style="margin: unset;">Creditor</h2>
            <h3 style="margin: unset; font-weight: bold; ">b4payment GmbH</h3>
            <p style="margin: unset;">Obermünsterstraße&nbsp;14</p>
            <p style="margin: unset;">93047&nbsp;Regensburg</p>
            <p style="margin: unset;">GERMANY</p>
            <br>
            <p style="margin: unset;" class="monospace">Creditor ID: DE36ZZZ00001690322</p>
        </div>
        <div class="sepa-debitor">
            <h2 style="margin: unset;">Debtor</h2>
            <h3 style="margin: unset; font-weight: bold; "><?php echo $billingInfo['customerName']; ?></h3>
            <div class="address" style="margin: unset;">
                <p style="margin: unset;" class="ng-star-inserted"><?php echo $billingInfo['billAddress1']; ?></p>
                <p style="margin: unset;"><?php echo $billingInfo['billAddress2'] . ', '. $billingInfo['billCity'] ; ?></p>
                <p style="margin: unset;"><?php echo $billingInfo['billCountry']; ?></p>
            </div>
            <br>
            <p class="monospace" style="margin: unset;" id="sepa-dd-bic"></p>
            <p class="monospace" style="margin: unset;" id="sepa-dd-iban"></p>
        </div>
    </div>
    <div class="sepa-par">
        <hr style="opacity: 0.3;">
        <p>By accepting this mandate form, you authorise (A) b4payment GmbH to send instructions to your bank to debit your account (B) your bank to debit your account in accordance with the instructions from b4payment GmbH.</p>
        <p>As part of your rights, you are entitled to a refund from your bank under the terms and conditions of your agreement with your bank. A refund must be claimed within 8 weeks starting from the date on which your account was debited.
        </p>
        <div class="sepa-checkbox-container" id="sepa-checkbox-container">
            <label class="sepa-checkbox-layout" for="sepa-checkbox-input">
                <div class="sepa-checkbox-inner-container">
                    <input class="sepa-checkbox-input" type="checkbox" id="sepa-checkbox-input" required>
                </div>
                <span class="sepa-checkbox-layout">
                    <span style="display:none">&nbsp;</span>
                    <h4 style="font-size: 12px;">I accept the mandate for a single payment</h4>
                </span>
            </label>
        </div>
    </div>

    <div class="sepa-right">
        <hr style="opacity: 0.3;">
        <div class="sepa-card-footer">
            <div class="sepa-card-footer-text">
                <div class="sepa-footer-title">
                    Your rights regarding the above mandate are explained in a statement that you can obtain from your bank.
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

	// Checkout if apple pay was selected
    if (jQuery('#p_method_checkoutcomapplepay').length > 0) {
        if ($('p_method_checkoutcomapplepay').checked) {
            // Call method from checkoutcomapplepay to separate logic
            checkoutInitialiseApplePay();
        }
    }

    // Check if google pay was selected
    if (jQuery('#p_method_checkoutcomgooglepay').length > 0) {
        if ($('p_method_checkoutcomgooglepay').checked) {
            googlePayTransactionController.init();
        }
    }

    // Check if sepa was selected
    if (jQuery('#cko-apms-sepa').length > 0 && $('cko-apms-sepa').checked) {
        // Show sepa mandate
        jQuery('.sepa-mandate-card').show();
        document.getElementById("sepa-dd-bic").innerHTML = 'BIC : ' + jQuery('#sepa-bic').val();
        document.getElementById("sepa-dd-iban").innerHTML = 'IBAN : ' + jQuery('#sepa-iban').val();
    }

    // Check if card payment was selected
    if(jQuery('#p_method_checkoutcomcards').length > 0 && $('p_method_checkoutcomcards').checked) {
        // hide sepa mandate
        jQuery('.sepa-mandate-card').hide();
    }

	//Check if magento default place order button exist
	if (jQuery('#review-buttons-container').length > 0) {
		var button = jQuery('#review-buttons-container')[0].down('button');
		//Remove onclick event
		button.writeAttribute('onclick', '');

		// On place order button click
		jQuery('#review-buttons-container').on('click', function () {
			// Check if checkout.com exist
			if (jQuery('#p_method_checkoutcomcards').length > 0) {
				//Check if checkout.com is selected
				if ($('p_method_checkoutcomcards').checked) {
                    if(jQuery('#cko-new-card').length > 0){
                        if($('cko-new-card').checked){
                            Frames.submitCard();
                        } else {
                            document.getElementById('cko-card-token').value = ''
                            review.save();
                        }
                    } else {
                        Frames.submitCard();
                    }
				} else if(jQuery('#p_method_checkoutcomapms').length > 0){
                    if($('p_method_checkoutcomapms').checked) {
                        if (jQuery('#cko-apms-boleto').length > 0 && $('cko-apms-boleto').checked) {
                            document.getElementById('cko-boleto-date').value = document.getElementById('boleto-date').value;
                            document.getElementById('cko-cpf').value = document.getElementById('cpf').value;
                            document.getElementById('cko-cust-name').value = document.getElementById('cust-name').value;
                            review.save();
                        } else if(jQuery('#cko-apms-ideal').length > 0 && $('cko-apms-ideal').checked) {
                            document.getElementById('cko-ideal-bic').value = document.getElementById('issuer-id').value
                            review.save();
                        } else if(jQuery('#cko-apms-giropay').length > 0 && $('cko-apms-giropay').checked) {
                            document.getElementById('cko-giropay-bank').value = document.getElementById('giropay-id').value
                            review.save();
                        } else if(jQuery('#cko-apms-sepa').length > 0 && $('cko-apms-sepa').checked) {
                            if(!$('sepa-checkbox-input').checked) {
                                alert('Please accept the mandate a for single payment.');
                            } else {
                                review.save();
                            }
                        }else if(jQuery('#cko-apms-klarna').length > 0 && $('cko-apms-klarna').checked) {
                            try {
                                Klarna.Payments.authorize(
                                    // options
                                    {
                                        instance_id: "klarna-payments-instance" // Same as instance_id set in Klarna.Payments.load().
                                    },
                                    // callback
                                    function (response) {
                                        document.getElementById('cko-klarna-token').value = response.authorization_token;
                                        review.save();
                                    }
                                );
                            } catch (e) {
                                // Handle error. The authorize~callback will have been called
                                // with "{ show_form: false, approved: false }" at this point.
                                console.log(e);
                            }
                        } else {
                            review.save();
                        }
                    } else {
                        review.save();
                    }
                } else {
					review.save();
				}
			} else {
				review.save();
			}
		});
	}
</script>
