<?php
    $params = $this->getPostParams();
    $url    = $this->getPostUrl();
?>
<p><center><?php echo $this->__('You will be redirected to the payment gateway.');?></center></p>
<p><center><img src="<?php echo $this->getSkinUrl('images/checkoutApi/load.gif');?>" /></center></p>
<form id="payment-form" style="display:none" action="<?php echo $url?>" method="POST">
    <input name="publicKey" value="<?php echo $params['publicKey'] ?>"/>
    <input name="paymentToken" value="<?php echo $params['paymentToken'] ?>"/>
    <input name="customerEmail" value="<?php echo $params['customerEmail'] ?>"/>
    <input name="customerName" value="<?php echo htmlspecialchars($params['customerName'], ENT_QUOTES) ?>"/>
    <input name="value" value="<?php echo $params['value'] ?>"/>
    <input name="currency" value="<?php echo $params['currency'] ?>"/>
    <input name="cardFormMode" value="<?php echo $params['cardFormMode'] ?>"/></input>
    <input name="paymentMode" value="<?php echo $params['paymentMode'] ?>"/>
    <input name="environment" value="<?php echo $params['environment'] ?>"/>
    <input name="redirectUrl" value="<?php echo $params['redirectUrl'] ?>"/>
    <input name="cancelUrl" value="<?php echo $params['redirectUrl'] ?>"/>
    <input name="contextId" id="contextId" value="<?php echo $params['contextId'] ?>"/>
    <input name="billingDetails" id="billingDetails"/>
    <input name="useCurrencyCode" value="<?php echo $params['useCurrencyCode'] ?>"/>
    <input name="logoUrl" value="<?php echo $params['logoUrl'] ?>"/>
    <input name="themeColor" value="<?php echo $params['themeColor'] ?>"/>
    <input name="iconColor" value="<?php echo $params['iconColor'] ?>"/>
    <input name="title" value="<?php echo $params['title'] ?>"/>
    <input name="subtitle" value="<?php echo $params['subtitle'] ?>"/>
    <input name="theme" value="<?php echo $params['theme'] ?>"/>
    <input name="localisation" value="<?php echo $params['localisation'] ?>"/>
    
</form>
<script>
    (function () {
        var config = {
            "addressLine1"  : "<?php echo htmlspecialchars($params['billingDetails']['addressLine1'], ENT_QUOTES);?>",
            "addressLine2"  : "<?php echo htmlspecialchars($params['billingDetails']['addressLine2'], ENT_QUOTES);?>",
            "postcode"      : "<?php echo htmlspecialchars($params['billingDetails']['postcode'], ENT_QUOTES);?>",
            "country"       : "<?php echo htmlspecialchars($params['billingDetails']['country'], ENT_QUOTES);?>",
            "city"          : "<?php echo htmlspecialchars($params['billingDetails']['city'], ENT_QUOTES);?>",
            "state"         : "<?php echo htmlspecialchars($params['billingDetails']['state'], ENT_QUOTES);?>",
        };

        <?php if(!empty($params['billingDetails']['phone'])):?>
            config.phone = {"number": '<?php echo htmlspecialchars($params['billingDetails']['phone']['number'], ENT_QUOTES);?>'};
        <?php endif;?>

        document.getElementById('billingDetails').value = JSON.stringify(config);

        document.getElementById('payment-form').submit();
    }());
</script>
