<?php
/**
 * Template for checkout page
 *
 * @version 20160203
 */
?>
<?php
$isJs           = $this->isFramesPaymentMethod();
$_controller    = Mage::app()->getFrontController()->getRequest()->getControllerName();
$_code          = $this->getPaymentCode();
$currentCode    = Mage::app()->getStore()->getCurrentCurrencyCode();
$baseCode       = Mage::app()->getStore()->getBaseCurrencyCode();

?>
<?php if($isJs): ?>
    <script type="text/javascript">
        window.jsCheckoutApi = new checkoutApi(
            '<?php echo $_code ?>',
            '<?php echo $_controller ?>',
            null
        );

        <?php if ($currentCode !== $baseCode):?>
        $$('#checkout-review-table tfoot tr').last().hide();
        <?php endif ?>
    </script>
<?php endif?>

<div id="ckoModal" class="ckoModal" >
                    <!-- Modal content -->
    <div class="cko-modal-content">
        <span class="close" onclick="document.getElementById('ckoModal').hide();">x</span>
        <p><h1><span  id="lpName"></span ></h1></p>
        <br>
        <br>
        <div id="idealInfo" style="display: none;">
            <label for="issuerId" >Issuer ID
            <select id="issuer">
                <?php foreach($this->getLocalPaymentInformation() as $key => $value ): ?>
                        <option value="<?php echo $value->value; ?>"><?php echo $value->key;?></option>
                <?php endforeach;?>
            </select>
        </label>
        </div>
        <div id="boletoInfo" style="display: none;">
            <div class="boleto-row"><label for="boletoDate" >Date of birth</label>
            <input type="date" id="boletoDate" name="boletoDate" /></div>
            <div class="boleto-row"></div>
            <div class="boleto-row"><label for="cpf" >CPF</label>
            <input type="text" id="cpf" name="cpf" /></div>
            <div class="boleto-row"></div>
            <div class="boleto-row"><label for="custName" ">Customer Name</label>
            <input type="text" id="custName" name="custName" required /></div>
        </div>
        <div id="qiwiInfo" style="display: none;">
            <label for="walletId">Wallet Id
                <input type="text" id="walletId" name="walletId" placeholder="+44 phone number" />
            </label>
        </div>
        <button type="button" id="mybtn" style="margin-top: 50px;">Continue</button>
    </div>

    <script type="text/javascript">
        var modal = document.getElementById('ckoModal');

        //When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
           if (event.target == modal) {
               modal.style.display = "none";
           }
        }
    </script>
    
</div>