<?php
$publicKey = Mage::getModel('ckopayment/checkoutcomConfig')->getPublicKey();
?>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>">

    <input type="hidden" id="cko-card-token" name="payment[cko_card_token]" value="" />

    <div class="frames-container">
        <!-- Frames JS -->
        <script src="https://cdn.checkout.com/js/frames.js"></script>
        <!-- Frames configuration-->
        <script type="text/javascript">
            if($$('#p_method_checkoutcomcards').length > 0){
                if($('p_method_checkoutcomcards').checked){
                    $('p_method_checkoutcomcards').checked = false
                }
            }

            Frames.removeAllEventHandlers(Frames.Events.CARD_TOKENISED);
            Frames.removeAllEventHandlers(Frames.Events.CARD_VALIDATION_CHANGED);
            Frames.removeAllEventHandlers(Frames.Events.FRAME_ACTIVATED);
            Frames.removeAllEventHandlers(Frames.Events.READY);

            Frames.init({
                // debugMode:true,
                publicKey: '<?php echo $publicKey; ?>',
                containerSelector: '.frames-container',
                frameActivated: function () {
                    //loader.style.display = loader.style.display === 'none' ? '' : 'none';
                    if($$('#cko-iframe-id').length > 1) {
                        $$('#cko-iframe-id').first().remove();
                    }
                },
                cardTokenised: function (event) {
                    document.getElementById('cko-card-token').value = event.data.cardToken;
                    Frames.unblockFields();
                    order.submit();
                },
                cardTokenisationFailed: function (event) {
                    // catch the error
                    console.log(event);
                }
            });

            if ($$('#p_method_checkoutcomcards').length > 0) {
                setTimeout(function () {
                    var button = $$('.order-totals-bottom')[0].down('button');
                    button.writeAttribute('onclick', '');

                    $$('.payment-methods').invoke('observe', 'change', function(event){
                        if (event.target.id == 'p_method_checkoutcomcards'){
                            button.writeAttribute('onclick', '');
                            $$('.order-totals-bottom').invoke('observe','click',function(){
                                if (Frames.isCardValid()) {
                                    var custName = document.getElementById('order-billing_address_firstname').value + ' '
                                        + document.getElementById('order-billing_address_lastname').value
                                    Frames.setCustomerName(custName);
                                    Frames.submitCard();
                                } else {
                                    alert("Please check your card details");
                                }
                            })
                        } else {
                            button.writeAttribute('onclick', 'order.submit()');
                        }
                    })
                },1000);
            }
        </script>
    </div>
</div>