<?php
$publicKey = Mage::getModel('ckopayment/checkoutcomConfig')->getPublicKey();
?>

<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>">
    <input type="hidden" id="cko-card-token" name="payment[cko_card_token]" value="" />

    <!-- FramesV2 payment form -->
    <div class="frames-container" id="frames-container" style="display:block">
        <div class="input-container card-number">
            <div class="icon-container">
                <img id="icon-card-number" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/card.svg');?>" alt="PAN" />
            </div>
            <div class="card-number-frame"></div>
            <div class="icon-container payment-method">
                <img id="logo-payment-method" />
            </div>
            <div class="icon-container">
                <img id="icon-card-number-error" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/error.svg');?>" />
            </div>
        </div>

        <div class="date-and-code">
            <div>
                <div class="input-container expiry-date">
                    <div class="icon-container">
                        <img id="icon-expiry-date" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/exp-date.svg');?>" alt="Expiry date" />
                    </div>
                    <div class="expiry-date-frame"></div>
                    <div class="icon-container">
                        <img id="icon-expiry-date-error" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/error.svg');?>" />
                    </div>
                </div>
            </div>
            <div>
                <div class="input-container cvv">
                    <div class="icon-container">
                        <img id="icon-cvv" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/cvv.svg');?>" alt="CVV" />
                    </div>
                    <div class="cvv-frame"></div>
                    <div class="icon-container">
                        <img id="icon-cvv-error" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/error.svg');?>"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
        <script type="text/javascript">
            // Initialise frames v2
            Frames.init({
                publicKey : "<?php echo $publicKey; ?>"
            });

            var logos = generateLogos();
            function generateLogos() {
                var logos = {};
                logos["card-number"] = {
                    src: "card",
                    alt: "card number logo"
                };
                logos["expiry-date"] = {
                    src: "exp-date",
                    alt: "expiry date logo"
                };
                logos["cvv"] = {
                    src: "cvv",
                    alt: "cvv logo"
                };
                return logos;
            }

            var errors = {};
            errors["card-number"] = "Please enter a valid card number";
            errors["expiry-date"] = "Please enter a valid expiry date";
            errors["cvv"] = "Please enter a valid cvv code";

            Frames.addEventHandler(
                Frames.Events.FRAME_VALIDATION_CHANGED,
                onValidationChanged
            );

            function onValidationChanged(event) {
                var e = event.element;

                if (event.isValid || event.isEmpty) {
                    if (e == "card-number" && !event.isEmpty) {
                        showPaymentMethodIcon();
                    }
                    setDefaultIcon(e);
                    clearErrorIcon(e);
                } else {
                    if (e == "card-number") {
                        clearPaymentMethodIcon();
                    }
                    setDefaultErrorIcon(e);
                    setErrorIcon(e);
                }
            }

            function clearErrorMessage(el) {
                var selector = ".error-message__" + el;
                var message = document.querySelector(selector);
                message.textContent = "";
            }

            function clearErrorIcon(el) {
                var logo = document.getElementById("icon-" + el + "-error");
                logo.style.removeProperty("display");
            }

            function showPaymentMethodIcon(parent, pm) {
                if (parent) parent.classList.add("show");

                var logo = document.getElementById("logo-payment-method");
                if (pm) {
                    var name = pm.toLowerCase();
                    var test = "<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/'); ?>";
                    logo.setAttribute("src", test + name + ".svg");
                    logo.setAttribute("alt", pm || "payment method");
                }
                logo.style.removeProperty("display");
            }

            function clearPaymentMethodIcon(parent) {
                if (parent) parent.classList.remove("show");

                var logo = document.getElementById("logo-payment-method");
                logo.style.setProperty("display", "none");
            }

            function setErrorMessage(el) {
                var selector = ".error-message__" + el;
                var message = document.querySelector(selector);
                message.textContent = errors[el];
            }

            function setDefaultIcon(el) {
                var selector = "icon-" + el;
                var logo = document.getElementById(selector);
                var test = "<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/'); ?>";
                logo.setAttribute("src", test + logos[el].src + ".svg");
                logo.setAttribute("alt", logos[el].alt);
            }

            function setDefaultErrorIcon(el) {
                var selector = "icon-" + el;
                var logo = document.getElementById(selector);
                var test = "<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/'); ?>";
                logo.setAttribute("src", test + logos[el].src + "-error.svg");
                logo.setAttribute("alt", logos[el].alt);
            }

            function setErrorIcon(el) {
                var logo = document.getElementById("icon-" + el + "-error");
                logo.style.setProperty("display", "block");
            }

            Frames.addEventHandler(
                Frames.Events.CARD_VALIDATION_CHANGED,
                cardValidationChanged
            );  
            function cardValidationChanged(event) {
                if(Frames.isCardValid())
                    Frames.submitCard();
            }

            Frames.addEventHandler(Frames.Events.CARD_TOKENIZED, onCardTokenized);
            function onCardTokenized(event) {
                console.log(event.token);
                document.getElementById('cko-card-token').value = event.token;
                Frames.enableSubmitForm();

                var button_bottom = $$('.order-totals-bottom')[0].down('button');
                document.getElementById(button_bottom.id).disabled = false;
                document.getElementById('submit_order_top_button').disabled = false;
            }

            Frames.addEventHandler(
                Frames.Events.PAYMENT_METHOD_CHANGED,
                paymentMethodChanged
            );
            
            function paymentMethodChanged(event) {
                var pm = event.paymentMethod;
                let container = document.querySelector(".icon-container.payment-method");

                if (!pm) {
                    clearPaymentMethodIcon(container);
                } else {
                    clearErrorIcon("card-number");
                    showPaymentMethodIcon(container, pm);
                }
            }
            // End frames v2

            methodChange();
            function methodChange(){
                setTimeout(function () {
                    var button_bottom = $$('.order-totals-bottom')[0].down('button');
                    document.getElementById(button_bottom.id).disabled = true;
                    document.getElementById('submit_order_top_button').disabled = true;
            
                    if ($$('#p_method_checkoutcomcards').length > 0) {
                   
                        if(!document.getElementById("p_method_checkoutcomcards").checked){
                            document.getElementById('frames-container').style.display = "none";
                            document.getElementById(button_bottom.id).disabled = false;
                            document.getElementById('submit_order_top_button').disabled = false;
                        }

                        $$('.payment-methods').invoke('observe', 'change', function(event){
                            if (event.target.id == 'p_method_checkoutcomcards'){
                                document.getElementById('frames-container').style.display = "block";
                                document.getElementById(button_bottom.id).disabled = true;
                                document.getElementById('submit_order_top_button').disabled = true;
                            } else {
                                document.getElementById('frames-container').style.display = "none";
                                document.getElementById(button_bottom.id).disabled = false;
                                document.getElementById('submit_order_top_button').disabled = false;
                            }
                        });
                    }
                },1500);
            }
        </script>
</div>