export default {
  value: {
    url: {
      magento_base: 'https://integrationcko.ngrok.io/magento',
      admin_path: '/index.php/admin',
      payments_path: '/index.php/admin/system_config/edit/section/payment/',
      product_path: '/index.php/test.html',
      three_d_downgrade_product: '/index.php/simulateno3d.html',
      cache: '/index.php/admin/cache/',
      sign_in_path: '/index.php/customer/account/login/',
      sign_out_path: '/index.php/customer/account/logout/',
      sign_up_path: '/index.php/customer/account/create/',
      saved_cards: '/index.php/ckopayment/cards/'
    },
    admin: {
      username: 'integration',
      password: 'Checkout1!',
      three_d_password: 'Checkout1!',
      secret_key: 'sk_test_6ac3b39d-43ab-41a8-be79-37a06f871385',
      public_key: 'pk_test_2a323408-4e0a-4fc9-9ad7-7fcb54ec9c8d',
      private_shared_key: '677b0db6-8fe7-4cc3-ae53-ff00df2abfcd',
    },
    guest: {
      email: 'john@smith.com',
      name: 'John',
      lastname: 'Smith',
      address: '42 Ealing Broadway',
      city: 'City',
      county: '1',
      postcode: '85001',
      phone: '07123456789',
    },
    customer: {
      email: 'test@checkout.com',
      name: 'Test',
      lastname: 'Checkout',
      street: '1 Wall Street',
      city: 'London',
      postcode: 'w1w w1w',
      country: 'GB',
      phone: '07987654321',
      password: 'Checkout17',
    },
    card: {
      visa: {
        card_number: '4242424242424242',
        month: '06',
        year: '28',
        cvv: '100',
      },
      mastercard: {
        card_number: '5436031030606378',
        month: '06',
        year: '25',
        cvv: '257',
      },
      amex: {
        card_number: '345678901234564',
        month: '06',
        year: '25',
        cvv: '1051',
      },
      diners: {
        card_number: '30123456789019',
        month: '06',
        year: '25',
        cvv: '257',
      },
      jcb: {
        card_number: '3530111333300000',
        month: '06',
        year: '28',
        cvv: '100',
      },
      discover: {
        card_number: '6011111111111117',
        month: '06',
        year: '28',
        cvv: '100',
      },
    },
    timeout_out: 120000,
    resolution_w: 1920,
    resolution_h: 3000,
    success: {
      title: 'Your order has been received.'
    },
    card_payment_option_title: 'Checkout via card',
    saved_cards_option_title: 'Checkout via your saved cards',
    saved_card_helper_label: 'Save this card',
  },
  selector: {
    frontend: {
      create_account: {
        create_button: '.col-1 > div:nth-child(2) > a:nth-child(1)',
        first_name: '#firstname',
        last_name: '#lastname',
        email: '#email_address',
        password: '#password',
        confirm_password: '#confirmation',
        register: 'button.button:nth-child(2)',
        address_book: 'div.block-content:nth-child(2) > ul:nth-child(1) > li:nth-child(3) > a:nth-child(1)',
        phone: '#telephone',
        street: '#street_1',
        city: '#city',
        state: '#region_id',
        postcode: '#zip',
        save_account: 'button.button:nth-child(2)',
        remove_saved_card: '.data-table > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(3) > a:nth-child(1)'
      },
      login: {
        email: '#email',
        password: '#pass',
        loginButton: '#send2'
      },
      order: {
        product_add: '.btn-cart',
        go_checkout: '.top > li:nth-child(1) > button:nth-child(1)',
        continue_guest: '#onepage-guest-register-button',
        firstname: '#billing-new-address-form > div:nth-child(1) > ul:nth-child(2) > li:nth-child(1) > div:nth-child(1) > div:nth-child(1) > div:nth-child(2) > input:nth-child(1)',
        lastname: '#billing-new-address-form > div:nth-child(1) > ul:nth-child(2) > li:nth-child(1) > div:nth-child(1) > div:nth-child(3) > div:nth-child(2) > input:nth-child(1)',
        email: '#billing-new-address-form > div:nth-child(1) > ul:nth-child(2) > li:nth-child(2) > div:nth-child(2) > div:nth-child(2) > input:nth-child(1)',
        address: '#billing-new-address-form > div:nth-child(1) > ul:nth-child(2) > li:nth-child(3) > div:nth-child(2) > input:nth-child(1)',
        city: '#billing-new-address-form > div:nth-child(1) > ul:nth-child(2) > li:nth-child(5) > div:nth-child(1) > div:nth-child(2) > input:nth-child(1)',
        state: '#billing-new-address-form > div:nth-child(1) > ul:nth-child(2) > li:nth-child(5) > div:nth-child(2) > div:nth-child(2) > select:nth-child(1)',
        postcode: '#billing-new-address-form > div:nth-child(1) > ul:nth-child(2) > li:nth-child(6) > div:nth-child(1) > div:nth-child(2) > input:nth-child(1)',
        phone: '#billing-new-address-form > div:nth-child(1) > ul:nth-child(2) > li:nth-child(7) > div:nth-child(1) > div:nth-child(2) > input:nth-child(1)',
        go_shipping: '#billing-buttons-container > button:nth-child(1)',
        go_pay: '#shipping-method-buttons-container > button:nth-child(2)',
        go_review: '#payment-buttons-container > button:nth-child(2)',
        go_card_place_order: '.btn-checkout',
        card_option: '#p_method_checkoutcomcards',
        card_option_title: '#dt_method_checkoutcomcards > label:nth-child(2)',
        apms_option: '#p_method_checkoutcomapms',
        ideal: '#cko-apms-ideal',
        ideal_confirm_transaction: '.btnLink',
        googleplay_option: '#p_method_checkoutcomgooglepay',
        checkout_iframe_selector: '#cko-iframe-id',
        embedded_fields: {
          card_number: "input[data-checkout='card-number']",
          month: "input[data-checkout='expiry-month']",
          year: "input[data-checkout='expiry-year']",
          cvv: "input[data-checkout='cvv']",
        },
        three_d_password: '#txtPassword',
        three_d_submit: '#txtButton',
        success_page: '.page-title > h1:nth-child(1)',
        save_this_card: '#cko-save-card-check',
        saved_card_one: '#save-cards > li:nth-child(2) > input:nth-child(1)',
        new_card_option: '#cko-new-card',
        save_card_helper_label: '#cko-save-card-area > label:nth-child(1)',
        save_cards_option_label: '.save-card-title',
        cvv_input: '#cko_cc_cid'
      }
    },
    backend: {
      admin_username: '#username',
      admin_password: '#login',
      admin_login: '.form-button',
      save: 'div.content-header:nth-child(1) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > button:nth-child(1)',
      clear_cache: 'button.delete:nth-child(1)',
      all_in_one: '#payment_checkoutcom_group_all_in_one-head',
      configuration: {
        selector: '#payment_checkoutcomconfig-head',
        environment: '#payment_checkoutcomconfig_ckocom_environment',
        secret_key: '#payment_checkoutcomconfig_ckocom_sk',
        public_key: '#payment_checkoutcomconfig_ckocom_pk',
        private_shared_key: '#payment_checkoutcomconfig_ckocom_psk',
        payment_action: '#payment_checkoutcomconfig_ckocom_card_autocap',
        capture_delay: '#payment_checkoutcomconfig_ckocom_card_delay',
        auth_order_status: '#payment_checkoutcomconfig_ckocom_order_authorised',
        capture_order_status: '#payment_checkoutcomconfig_ckocom_order_captured',
        flagged_order_status: '#payment_checkoutcomconfig_ckocom_order_flagged',
        refund_order_status: '#payment_checkoutcomconfig_ckocom_order_refunded',
        void_order_status: '#payment_checkoutcomconfig_ckocom_order_voided',
        create_invoice: '#payment_checkoutcomconfig_ckocom_create_invoice',
        credit_memo: '#payment_checkoutcomconfig_ckocom_credit_memo',
      },
      card: {
        selector: '#payment_checkoutcomcards-head',
        enable: '#payment_checkoutcomcards_active',
        option_title: '#payment_checkoutcomcards_title',
        threed: '#payment_checkoutcomcards_ckocom_card_threed',
        attemptN3D: '#payment_checkoutcomcards_ckocom_card_notheed',
        saved_cards: '#payment_checkoutcomcards_ckocom_card_saved',
        saved_cards_title: '#payment_checkoutcomcards_ckocom_card_saved_title',
        saved_card_label: '#payment_checkoutcomcards_ckocom_card_saved_label',
        dynamic_descriptor: '#payment_checkoutcomcards_ckocom_card_desctiptor',
        descriptor_name: '#payment_checkoutcomcards_ckocom_card_desctiptor_name',
        descriptor_city: '#payment_checkoutcomcards_ckocom_card_desctiptor_city',
        mada: '#payment_checkoutcomcards_ckocom_card_mada',
        require_cvv: '#payment_checkoutcomcards_ckocom_require_cvv',
      },
      apms: {
        selector: '#payment_checkoutcomapms-head',
        enable: '#payment_checkoutcomapms_active',
        apms_selector: "#payment_checkoutcomapms_ckocom_apms_selector"
      }
    },
  },
};
