<?php
/**
 * Template for checkout page
 *
 * @version 20160202
 */
?>
<?php $isActive = $this->isActive();?>
<?php if ($isActive):?>
    <?php $tokenResult = $this->getPaymentTokenResult(); ?>
    <?php if (!empty($tokenResult)): ?>
        <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
            <?php if ($tokenResult['success']):?>
                <li id="payment_form_<?php echo $this->getMethodCode() ?>_block" class="checkout-widget"></li>
                <li>
                    <input type="hidden" id="cko-card-token" name="payment[checkout_card_token]" value=""/>
                    <input type="hidden" id="cko-lp-redirectUrl" name="payment[lp_redirect_url]" value=""/>
                    <input type="hidden" id="cko-lp-lpName" name="payment[lp_name]" value=""/>
                    <script type="text/javascript">
                        window.checkoutIntegrationTotalValue = '<?php echo $tokenResult['value'];?>';

                        window.checkoutIntegrationCurrentConfig = {
                            debugMode: '<?php echo $this->getDebugMode() ? 'true' : 'false';?>',
                            renderMode: <?php echo $this->getRenderMode() ?>,
                            publicKey: '<?php echo $this->getPublicKey();?>',
                            paymentToken: '<?php echo $tokenResult['token'];?>',
                            customerEmail: '<?php echo $tokenResult['customerEmail'];?>',
                            customerName: '<?php echo $tokenResult['customerName'];?>',
                            value: '<?php echo $tokenResult['value'];?>',
                            currency: '<?php echo $tokenResult['currency'];?>',
                            widgetContainerSelector: '#payment_form_<?php echo $this->getMethodCode() ?>_block',
                            paymentMode: '<?php echo $this->getPaymentMode();?>',
                            logoUrl: '<?php echo $this->getLogoUrl();?>',
                            themeColor: '<?php echo $this->getThemeColor();?>',
                            useCurrencyCode: '<?php echo $this->isUseCurrencyCode() ? 'true' : 'false';?>',
                            title: '<?php echo $this->getTitle();?>',
                            formButtonLabel: '<?php echo $this->__('Continue') ?>',
                            buttonLabel: '<?php echo $this->__('Add Card') ?>',
                            enableIframePreloading : false,
                            styling: {
                                formButtonColor: '<?php echo $this->getFormButtonColor();?>',
                                formButtonColorLabel: '<?php echo $this->getFormButtonColorLabel();?>',
                                overlayShade: '<?php echo $this->getOverlayShade();?>',
                                overlayOpacity: '<?php echo $this->getOverlayOpacity();?>'
                            },
                            cardFormMode: '<?php echo $this->getCardFormMode();?>',
                                lpCharged: {
                                    callback: function (event) {
                                        document.getElementById('cko-lp-redirectUrl').value = event.data.redirectUrl;
                                        document.getElementById('cko-lp-lpName').value = event.data.lpName;
                                        $$('.validate-card-token')[0].value = 'true';
                                        Validation.validate($$('.validate-card-token')[0]);

                                        if (typeof payment != 'undefined' && typeof payment.save == 'function') {
                                            payment.save();
                                        }
                                    },
                                    options: {
                                        removeOverlayOnRedirect: true
                                    }
                            },
                            cardTokenised: function (event) {
                                if (document.getElementById('cko-card-token').value.length === 0 || document.getElementById('cko-card-token').value != event.data.cardToken) {
                                    document.getElementById('cko-card-token').value = event.data.cardToken;
                                    $$('.validate-card-token')[0].value = 'true';
                                    Validation.validate($$('.validate-card-token')[0]);

                                    if (typeof payment != 'undefined' && typeof payment.save == 'function') {
                                        payment.save();
                                    }
                                }
                            }
                        };

                        window.checkoutIntegrationIsReady = window.checkoutIntegrationIsReady || false;
                        if (!window.checkoutIntegrationIsReady) {
                            window.CKOConfig = {
                                ready: function () {
                                    if (window.checkoutIntegrationIsReady) {
                                        return false;
                                    }

                                    if (typeof CKOAPIJS == 'undefined') {
                                        return false;
                                    }

                                    CKOAPIJS.render(window.checkoutIntegrationCurrentConfig);

                                    window.checkoutIntegrationIsReady = true;
                                }
                            };

                            var script = document.createElement('script');
                            script.src = '<?php echo $this->getJsPath();?>';
                            script.async = true;
                            script.setAttribute('data-namespace', 'CKOAPIJS');
                            document.head.appendChild(script);

                            var script = document.createElement('script');
                            script.src = '<?php echo $this->getCheckoutJsPath();?>';
                            script.async = false;
                            document.head.appendChild(script);
                        } else {
                            CKOAPIJS.render(window.checkoutIntegrationCurrentConfig);
                        }
                    </script>
                </li>
                <li>
                    <input class="validate-card-token" type="hidden">
                    <script type="text/javascript">
                        Validation.add('validate-card-token','<?php echo $this->__('Please use the "Add Card" button to complete your payment.') ?>',function(v){
                            return v === '' ? false : true;
                        });
                    </script>
                </li>
            <?php else:?>
                <li><?php echo $this->__($tokenResult['message']) ?></li>
            <?php endif?>
        </ul>
    <?php else:?>
        <script type="text/javascript">
            window.checkoutIntegrationTotalValue = 0;
        </script>
    <?php endif;?>
<?php else :?>
    <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li><?php echo $this->__('Selected Payment Type is not allowed.') ?></li>
    </ul>
<?php endif?>
