<?php
/**
 * Template for checkout page
 *
 * @version 20160202
 */
?>
<?php $isActive = $this->isActive();?>
<?php if ($isActive):?>
    <?php $tokenResult = $this->getPaymentTokenResult(); ?>
    <?php if (!empty($tokenResult)): ?>
        <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
            
            <?php if($this->isCustomerLogged() && $this->isSaveCard() && $this->getPaymentMode() != 'localpayments' ): ?>
                <?php $cardList = $this->getCustomerCardList();?>
                <?php if(!empty($cardList)): ?>
                    <?php foreach($cardList as $index => $card):?>
                        <li>
                            <input class="checkoutapi-saved-card validate-one-required-by-name" type="radio" id="card-<?php echo $index;?>" value="<?php echo $card['value'];?>" name="payment[customer_card]"/>
                            <label for="card-<?php echo $index;?>"><?php echo $card['type'] . ' ' . $card['title'];?></label>
                        </li>
                    <?php endforeach;?>
                    <?php if($this->cvvVerification()):?>
                            <div class="cvvVerification">
                                <label class="required" for="<?php echo $this->getMethodCode() ?>_cc_cid"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                                <div class="input-box">
                                    <div class="v-fix">
                                        <input type="text" value="" name="payment[cc_id]" id="<?php echo $this->getMethodCode() ?>_cc_id" class="input-text cvv required-entry validate-cc-cvn" title="Card Verification Number" pattern="\d*" autocomplete="off" value="<?php echo $this->getCcid();?>">
                                    </div>
                                    <a class="cvv-what-is-this" href="#"><?php echo $this->__('What is this?') ?></a>
                                </div>
                            </div>

                    <?php endif;?>
                    <li>
                        <input id="checkoutapi-new-card" class="validate-one-required-by-name" type="radio" name="payment[customer_card]" value="new_card"/>
                        <label for="checkoutapi-new-card">Use New Card</label>
                    </li>
                <?php endif;?>
            <?php endif;?>

            <?php if ($tokenResult['success']):?>
                <li id="payment_form_<?php echo $this->getMethodCode() ?>_block"></li>
                <li>
                    <script type="text/javascript">
                        window.checkoutIntegrationHostedConfig = {
                            debugMode: 'false',
                            renderMode: <?php echo $this->getRenderMode() ?>,
                            publicKey: '<?php echo $this->getPublicKey();?>',
                            paymentToken: '<?php echo $tokenResult['token'];?>',
                            customerEmail: '<?php echo $tokenResult['customerEmail'];?>',
                            customerName: '<?php echo $tokenResult['customerName'];?>',
                            value: '<?php echo $tokenResult['value'];?>',
                            currency: '<?php echo $tokenResult['currency'];?>',
                            widgetContainerSelector: '#payment_form_<?php echo $this->getMethodCode() ?>_block',
                            paymentMode: '<?php echo $this->getPaymentMode();?>',
                            widgetColor: '#333',
                            cardFormMode: '<?php echo $this->getCardFormMode();?>',
							showMobileIcons: true,
                        };

                        window.checkoutHostedIntegrationIsReady = window.checkoutHostedIntegrationIsReady || false;
                        if (!window.checkoutHostedIntegrationIsReady) {
                            setTimeout(function(){ 
                                window.CKOConfig = {
                                    namespace: 'CKOAPIHOSTED',
                                    ready: function () {

                                        if (window.checkoutHostedIntegrationIsReady) {
                                            return false;
                                        }

                                        if (typeof CKOAPIHOSTED == 'undefined') {
                                            return false;
                                        }

                                        CKOAPIHOSTED.render(window.checkoutIntegrationHostedConfig);

                                        window.checkoutHostedIntegrationIsReady = true;
                                    }
                                };

                                var script = document.createElement('script');
                                script.type = "text/javascript";
                                script.src = '<?php echo $this->getHostedJsPath();?>';
                                script.async = true;
                                document.head.appendChild(script);
                            }, 3000);
                        } else {
                            CKOAPIHOSTED.render(window.checkoutIntegrationHostedConfig);
                        }
                    </script>
                </li>
            <?php else:?>
                <li><?php echo $this->__($tokenResult['message']) ?></li>
            <?php endif?>
            <li class="checkoutapi-save-card-check">
                <label for="<?php echo $this->getMethodCode() ?>_save_card_check"><?php echo $this->__('Save card for future payments. ') ?></label>
                <input type="checkbox" name="payment[save_card_check]" id="<?php echo $this->getMethodCode() ?>_save_card_check" value='1'>           
            </li>
        </ul>
    <?php endif;?>
    <?php if (!empty($cardList)):?>
        <script type="application/javascript">
            hideNewCard();

            $$('.checkoutapi-saved-card').invoke('observe', 'change', hideNewCard);
            $('checkoutapi-new-card').observe('change', showNewCard);

            function hideNewCard() {
                $$('.checkout-kit-card-block').each(Element.hide);
                $$('.checkoutapi-save-card-check').each(Element.hide);
            }

            function showNewCard() {
                $$('.checkout-kit-card-block').each(Element.show);
                $$('.checkoutapi-save-card-check').each(Element.show);
            }
        </script>
    <?php endif;?>
    <?php if(!$this->isCustomerLogged() || !$this->isSaveCard() || $this->getPaymentMode() == 'localpayments'):?>
            <script type="application/javascript">
                $$('.checkoutapi-save-card-check').each(Element.hide);
            </script>
        <?php endif;?>
        <?php if($this->cvvVerification()):?>
        <script type="application/javascript">
            hideCvvVerification();

            $$('.checkoutapi-saved-card').invoke('observe', 'change', showCvvVerification);
            $('checkoutapi-new-card').observe('change', hideCvvVerification);

            function hideCvvVerification() {
                $$('.cvvVerification').each(Element.hide);
            }

            function showCvvVerification() {
                $$('.cvvVerification').each(Element.show);
            }
        </script>
    <?php endif;?>
<?php else :?>
    <ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <li><?php echo $this->__('Selected Payment Type is not allowed.') ?></li>
    </ul>
<?php endif?>
