<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>">

    <!-- hidden input field to send card token   -->
    <input type="hidden" id="cko-card-token" name="payment[cko_card_token]" value="" />
    <input type="hidden" id="cko-card-bin" name="payment[cko_card_bin]" value="" />

    <div class="cko-container" id="cko-container" style="display: none">

        <!-- check if customer is logged in and if saved card is enable-->
        <?php if ($this->isCustomerLoggedIn() && $this->getIsSaveCardEnable()): ?>
        <div id="save-cards" class="save-cards" style="padding-left: 20px;">
            <!-- check if customer has saved cards -->
            <?php if (!empty($this->getCustomerCardList())): ?>
            <div class="save-card-title" style="padding-bottom: 10px;">
                <?php echo $this->getSaveCardTitle(); ?>
            </div>
            <?php foreach ($this->getCustomerCardList() as $index => $value): ?>

                    <?php if ($value['isMada']): ?>
                        <li class="checkout-saved-card-or-apm">
                            <input
                                    type="radio"
                                    class="checkout-saved-card-or-apm-input validate-one-required-by-name"
                                    id="mada-card-<?php echo $index; ?>" value="<?php echo $value['value']; ?>"
                                    name="payment[customer_card]"
                                    style="vertical-align:middle"
                            />
                            <img class="card-logo" src="<?php echo $this->getSkinUrl('images/checkoutcom/'.$value['type'].'.svg');?> "/>
                            <label class="checkout-saved-card-or-apm-info" for="mada-card-<?php echo $index; ?>">
                                <span class="card-dots">●●●●</span><?php echo $value['title']; ?>
                            </label>
                        </li>
                        <?php else: ?>
                        <li class="checkout-saved-card-or-apm">
                            <input
                                    type="radio"
                                    class="checkout-saved-card-or-apm-input validate-one-required-by-name"
                                    id="card-<?php echo $index; ?>" value="<?php echo $value['value']; ?>"
                                    name="payment[customer_card]"
                                    style="vertical-align:middle"
                            />
                            <img class="card-logo" src="<?php echo $this->getSkinUrl('images/checkoutcom/'.$value['type'].'.svg');?> "/>
                            <label class="checkout-saved-card-or-apm-info" for="card-<?php echo $index; ?>">
                                <span class="card-dots">●●●●</span><?php echo $value['title']; ?>
                            </label>
                        </li>

                    <?php endif;?>

            <?php endforeach;?>

                <div class="cvvVerification" style="display: none; padding-bottom: 10px;">
                    <label class="required" for="cko_cc_cid">
                        <em>*</em><?php echo $this->__('Card Verification Number') ?>
                    </label>
                    <div class="input-box">
                        <div class="v-fix">
                            <input type="text"
                                   value=""
                                   name="payment[cc_id]"
                                   id="cko_cc_cid"
                                   class="input-text cvv required-entry validate-cc-cvn"
                                   title="Card Verification Number"
                                   pattern="\d*"
                                   autocomplete="off"
                             />
                        </div>
                        <a class="cvv-what-is-this" href="#"><?php echo $this->__('What is this?') ?></a>
                    </div>
                </div>

                <?php if ($this->getIsCvvRequire()): ?>
                    <script type="text/javascript">
                        jQuery("#save-cards").click(function (event) {
                            if (event.target.id === "cko-new-card") {
                                $$('.cvvVerification').each(Element.hide);
                            } else {
                                $$('.cvvVerification').each(Element.show);
                                jQuery(".frames-container").hide();
                                jQuery("#cko-save-card-area").hide();
                            }
                        });
                    </script>
                <?php else: ?>
                    <script type="text/javascript">
                        jQuery("#save-cards").click(function (event) {
                            if (event.target.id === "cko-new-card") {
                                $$('.cvvVerification').each(Element.hide);
                            } else if (event.target.id.startsWith("mada-card-")) {
                                $$('.cvvVerification').each(Element.show);
                            } else  if (event.target.id.startsWith("card-")) {
                                $$('.cvvVerification').each(Element.hide);
                            }
                        });
                    </script>
                <?php endif;?>

                <script type="text/javascript">

                </script>
            <li class="checkout-saved-card-or-apm">
                <input
                    id="cko-new-card"
                    class="checkout-saved-card-or-apm-input validate-one-required-by-name"
                    type="radio"
                    name="payment[customer_card]"
                    value="new_card"
                    style="vertical-align:middle"
                />
                <img class="card-logo cko-add-card" >
                <label class="checkout-saved-card-or-apm-info" for="cko-new-card">
                    <span class="cko-new-card">New Card</span>
                </label>
            </li>
            <?php endif;?>
        </div>
        <?php endif;?>

        <div class="frames-container" id="frames-container">
            <!-- form will be added here -->
            <div id="cko-loader" class="main-loading-container">
                <div class="dots-fade">
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>

            <!-- FramesV2 payment form -->
            <div class="input-container card-number">
                <div class="icon-container">
                    <img id="icon-card-number" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/card.svg');?>" alt="PAN" />
                </div>
                <div class="card-number-frame"></div>
                <div class="icon-container payment-method">
                    <img id="logo-payment-method" />
                </div>
                <div class="icon-container">
                    <img id="icon-card-number-error" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/error.svg');?>" />
                </div>
            </div>

            <div class="date-and-code">
                <div>
                    <div class="input-container expiry-date">
                        <div class="icon-container">
                            <img id="icon-expiry-date" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/exp-date.svg');?>" alt="Expiry date" />
                        </div>
                        <div class="expiry-date-frame"></div>
                        <div class="icon-container">
                            <img id="icon-expiry-date-error" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/error.svg');?>" />
                        </div>
                    </div>
                </div>
                <div>
                    <div class="input-container cvv">
                        <div class="icon-container">
                            <img id="icon-cvv" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/cvv.svg');?>" alt="CVV" />
                        </div>
                        <div class="cvv-frame"></div>
                        <div class="icon-container">
                            <img id="icon-cvv-error" src="<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/error.svg');?>"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- save card checkbox -->
        <div class="save-card-checkbox" style="display: none">
            <li id="cko-save-card-area" class="cko-save-card-check">
                <label for="cko-save-card-check">
                    <input type="checkbox" name="payment[save_card_check]" id="cko-save-card-check" value='1'>
                    <?php echo $this->getSavedCardOption() ?>
                </label>
            </li>
        </div>

        <!-- check if customer is logged in and show save card checkbox-->
        <?php if ($this->isCustomerLoggedIn() && $this->getIsSaveCardEnable()): ?>
            <script type="text/javascript">
                jQuery('.save-card-checkbox').show();
            </script>
        <?php endif;?>

        <!-- check if customer is registering and show save card checkbox-->
        <script type="text/javascript">
            if(document.getElementById('login:register') != null){
                if (document.getElementById('login:register').checked) {
                    jQuery('.save-card-checkbox').show();
                }
            }
        </script>

    </div>
    <script>

        // When saved card are enabled hide Checkout.Frames
        if(jQuery('#cko-new-card').length > 0) {
            // Dont hide it in case is selected by default
            if(document.getElementById('cko-new-card').checked) {
                showFrames();
            } else {
                hideFrames();
            }
        }

        // Handle selecting a saved card and show frames only when the new card option is selected
        jQuery("#save-cards").click(function (event) {
            if (event.target.id === "cko-new-card") {
                showFrames();
            } else if (event.target.id.startsWith("card-")) {
                hideFrames();
            }
        });

        var loader = document.getElementById('cko-loader');

        // only show Checkout.Frames when the method is selected
        var methodSelector = document.getElementById('p_method_checkoutcomcards');
        var myForm = document.getElementById('cko-container');
        methodSelector.addEventListener('click', function () {
            myForm.style.display = methodSelector.checked ? '' : 'none';
        });

        // Frames v2 config
        Frames.init({
            publicKey : "<?php echo $this->getPublicKey(); ?>",
            frameActivated: function () {
               loader.style.display = loader.style.display === 'none' ? '' : 'none';
            },
        });

        var logos = generateLogos();
        function generateLogos() {
            var logos = {};
            logos["card-number"] = {
                src: "card",
                alt: "card number logo"
            };
            logos["expiry-date"] = {
                src: "exp-date",
                alt: "expiry date logo"
            };
            logos["cvv"] = {
                src: "cvv",
                alt: "cvv logo"
            };
            return logos;
        }

        var errors = {};
        errors["card-number"] = "Please enter a valid card number";
        errors["expiry-date"] = "Please enter a valid expiry date";
        errors["cvv"] = "Please enter a valid cvv code";

        Frames.addEventHandler(
            Frames.Events.FRAME_VALIDATION_CHANGED,
            onValidationChanged
        );
        function onValidationChanged(event) {
            var e = event.element;

            if (event.isValid || event.isEmpty) {
                if (e == "card-number" && !event.isEmpty) {
                    showPaymentMethodIcon();
                }
                setDefaultIcon(e);
                clearErrorIcon(e);
            } else {
                if (e == "card-number") {
                    clearPaymentMethodIcon();
                }
                setDefaultErrorIcon(e);
                setErrorIcon(e);
            }
        }

        function clearErrorMessage(el) {
            var selector = ".error-message__" + el;
            var message = document.querySelector(selector);
            message.textContent = "";
        }

        function clearErrorIcon(el) {
            var logo = document.getElementById("icon-" + el + "-error");
            logo.style.removeProperty("display");
        }

        function showPaymentMethodIcon(parent, pm) {
            if (parent) parent.classList.add("show");

            var logo = document.getElementById("logo-payment-method");
            if (pm) {
                var name = pm.toLowerCase();
                var test = "<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/'); ?>";
                logo.setAttribute("src", test + name + ".svg");
                logo.setAttribute("alt", pm || "payment method");
            }
            logo.style.removeProperty("display");
        }

        function clearPaymentMethodIcon(parent) {
            if (parent) parent.classList.remove("show");

            var logo = document.getElementById("logo-payment-method");
            logo.style.setProperty("display", "none");
        }

        function setErrorMessage(el) {
            var selector = ".error-message__" + el;
            var message = document.querySelector(selector);
            message.textContent = errors[el];
        }

        function setDefaultIcon(el) {
            var selector = "icon-" + el;
            var logo = document.getElementById(selector);
            var test = "<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/'); ?>";
            logo.setAttribute("src", test + logos[el].src + ".svg");
            logo.setAttribute("alt", logos[el].alt);
        }

        function setDefaultErrorIcon(el) {
            var selector = "icon-" + el;
            var logo = document.getElementById(selector);
            var test = "<?php echo $this->getSkinUrl('images/checkoutcom/card-icons/'); ?>";
            logo.setAttribute("src", test + logos[el].src + "-error.svg");
            logo.setAttribute("alt", logos[el].alt);
        }

        function setErrorIcon(el) {
            var logo = document.getElementById("icon-" + el + "-error");
            logo.style.setProperty("display", "block");
        }

        Frames.addEventHandler(
            Frames.Events.CARD_VALIDATION_CHANGED,
            cardValidationChanged
        );
        function cardValidationChanged(event) {
            if(Frames.isCardValid())
                Frames.submitCard();
        }

        Frames.addEventHandler(Frames.Events.CARD_TOKENIZED, onCardTokenized);
        function onCardTokenized(event) {
            document.getElementById('cko-card-token').value = event.token;
            document.getElementById('cko-card-bin').value = event.bin;
            Frames.enableSubmitForm()
        }

        Frames.addEventHandler(
            Frames.Events.PAYMENT_METHOD_CHANGED,
            paymentMethodChanged
        );
        function paymentMethodChanged(event) {
            var pm = event.paymentMethod;
            let container = document.querySelector(".icon-container.payment-method");

            if (!pm) {
                clearPaymentMethodIcon(container);
            } else {
                clearErrorIcon("card-number");
                showPaymentMethodIcon(container, pm);
            }
        }
        // end frames v2 config

        // Check if payment continue button exist
        if (jQuery('#payment-buttons-container').length > 0) {
            var button = jQuery('#payment-buttons-container')[0].down('button');
            //Remove onclick event
            button.writeAttribute('onclick', '');

            jQuery('#payment-buttons-container').on('click', function () {
                // Check if checkout.com exist
                if (jQuery('#p_method_checkoutcomcards').length > 0) {
                    //Check if checkout.com is selected
                    if ($('p_method_checkoutcomcards').checked) {
                        // Check if new cards is available
                        if (jQuery('#cko-new-card').length > 0) {
                            if ($('cko-new-card').checked) {
                                validateCard()
                            } else {
                                payment.save();
                            }
                        } else {
                            validateCard()
                        }
                    } else {
                        payment.save();
                    }
                } else {
                    payment.save();
                }
            });
        }

        function validateCard() {
            if (Frames.isCardValid()) {
                var customerName = "<?php echo $this->getCustomerName(); ?>";

                if (customerName.length <= 1) {
                    customerName = document.getElementById("billing:firstname").value + ' ' + document.getElementById("billing:lastname").value;
                }

                Frames.cardholder.name == customerName ;
                payment.save();
            } else {
                alert('Please enter your card details');
            }
        }

        function showFrames() {
            jQuery(".frames-container").show();
            jQuery("#cko-save-card-area").show();
        }

        function hideFrames() {
            jQuery(".frames-container").hide();
            jQuery("#cko-save-card-area").hide();
        }
    </script>

</div>
