<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>">

    <input type="hidden" id="cko-boleto-date" name="payment[cko-boleto-date]" value="" />
    <input type="hidden" id="cko-cpf" name="payment[cko-cpf]" value=""/>
    <input type="hidden" id="cko-cust-name" name="payment[cko-cust-name]" value="" />
    <input type="hidden" id="cko-ideal-bic" name="payment[cko-ideal-bic]" value="" />
    <input type="hidden" id="cko-giropay-bank" name="payment[cko-giropay-bank]" value="" />
    <input type="hidden" id="cko-klarna-token" name="payment[cko-klarna-token]" value="" />

    <div id="cko-apm-container" style="display: none;">
        <?php if (!empty($this->getAlternativePaymentMethods())): ?>
            <?php foreach ($this->getAlternativePaymentMethods() as $index => $value): ?>
                <li class="checkout-saved-card-or-apm">
                    <input
                        class="cko-apms checkout-saved-card-or-apm-input validate-one-required-by-name"
                        type="radio"
                        id="cko-apms-<?php echo $value; ?>"
                        value="<?php echo $value; ?>"
                        name="payment[cko_apms]"
                    />
                    <img class="card-logo apm-logo" src="<?php echo $this->getSkinUrl('images/checkoutcom/'.$value.'.svg');?>"/>
                    <label class="checkout-saved-card-or-apm-info apm-label"  for="cko-apms-<?php echo $value; ?>">
                        <?php
                            switch ($value) {
                                case "ideal":
                                    $value = "iDEAL";
                                    break;
                                case "sepa":
                                    $value = "SEPA Direct Debit";
                                    break;
                                case "eps":
                                    $value = "EPS";
                                    break;
                                default:
                                    $value = ucfirst($value);
                            }
                            echo $value;
                        ?>
                    </label>
                </li>

                <!-- Check if klarna is available-->
                <?php if ($value == 'Klarna'):
                    $klarnaSession = $this->createKlarnaSession();
                    if (!empty($klarnaSession->client_token)) {
                        $clientToken = $klarnaSession->client_token;
                        $paymentMethodCategories = $klarnaSession->payment_method_categories;
                    }
                ?>
                <?php endif; ?>
            <?php endforeach;?>
        <?php else: ?>
            <script type="text/javascript">
                jQuery('#dt_method_checkoutcomapms').hide();
            </script>
        <?php endif;?>
    </div>

    <!-- Boleto request form-->
    <div class="boleto-info" id="boleto-info" style="display: none;" >
        <div class="boleto-heading">
            <label>Please complete the below form before you continue.</label>
        </div>
        <div>
            <label for="boleto-date" >Date of birth
            <input type="date" id="boleto-date" name="boleto-date" style="width: 365px;"  class="boleto-date validate-one-required"/>
            </label>
        </div>
        <div>
            <label for="cpf" >CPF
            <input type="text" id="cpf" name="cpf" validate-one-required-by-name class="cpf validate-one-required"/>
            </label>
        </div>
        <div>
            <label for="cust-name">Customer Name
            <input type="text" id="cust-name" name="cust-name" class="cust-name validate-one-required"/>
            </label>
        </div>
    </div>

    <!-- Ideal bank info-->
    <div class="ideal-bank-info" id="ideal-bank-info" style="display: none;">
        <div class="ideal-heading">
            <label>Please select BIC from the list.</label>
        </div>
        <label for="issuer-id">
            <select id="issuer-id" name="payment[cko-ideal-bic]">
                <?php if (!empty($this->getIdealBankInfo())): ?>
                    <?php foreach ($this->getIdealBankInfo() as $value): ?>
                        <option value="<?php echo $value->bic; ?>"><?php echo $value->name; ?></option>
                    <?php endforeach;?>
                <?php endif;?>
            </select>
        </label>
    </div>

    <!-- giropay bank info-->
    <div class="giropay-bank-info" id="giropay-bank-info" style="display: none;">
        <div class="giropay-heading">
            <label>Please select a bank from the list.</label>
        </div>
        <label for="giropay-id">
            <select id="giropay-id">
                <?php if (!empty($this->getGiropayBankInfo())): ?>
                    <?php foreach ($this->getGiropayBankInfo() as $key => $value): ?>
                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                    <?php endforeach;?>
                <?php endif;?>
            </select>
        </label>
    </div>

    <!-- Klarna details-->
    <div class="klarna-details" style="display: none;">
        <script type="text/javascript">
            jQuery('#cko-apms-klarna').click(function () {
                window.klarnaAsyncCallback = function () {
                // This is where you start calling Klarna's JS SDK functions
                    try {
                        Klarna.Payments.init(
                            {
                                client_token: '<?php echo $clientToken; ?>'
                            }
                        );
                    } catch (e) {
                        console.log(e);
                    }
                };
            });
        </script>
        <script src="https://x.klarnacdn.net/kp/lib/v1/api.js" async></script>

        <div class="klarna_widgets">
            <?php if (!empty($paymentMethodCategories)): ?>
                <?php foreach ($paymentMethodCategories as $key => $value): ?>
                <label>
                    <input type="radio" class="klarna_widgets" id="<?php echo $value->identifier; ?>" name="klarna_widgets" value="<?php echo $value->identifier; ?>" style="opacity: 1;" >
                    <?php echo $value->name; ?> 
                </label>
                <?php endforeach?>
            <?php endif;?>
        </div>
        <!-- Display form based on widgets click -->
        <div id="klarna_container">
            <?php $cartInfo = $this->getCartInfo()?>

            <script type="text/javascript">
                jQuery("input:radio.klarna_widgets").change(function(event){
                    var cartInfo = <?php echo json_encode($cartInfo) ?>;

                    try {
                        Klarna.Payments.load(
                            // options
                            {
                                container: "#klarna_container",
                                payment_method_categories: [event.target.id],
                                instance_id: "klarna-payments-instance"
                            },
                            cartInfo,
                            // callback
                            function (response) {
                                // ...
                                Klarna.Payments.authorize(
                                    // options
                                    {
                                        instance_id: "klarna-payments-instance" // Same as instance_id set in Klarna.Payments.load().
                                    },
                                    // callback
                                    function (response) {
                                        document.getElementById('cko-klarna-token').value = response.authorization_token;
                                    }
                                );
                            }
                        );
                    } catch (e) {
                        // Handle error. The load~callback will have been called
                        // with "{ show_form: false }" at this point.
                        console.log(e);
                    }
                });
            </script>
        </div>
    </div>

    <!-- Sepa details-->
    <div class="sepa-info" id="sepa-info" style="display: none;" >
        <div class="sepa-heading">
            <label>Payment information</label>
        </div>
        <div>
            <label for="sepa-iban" >IBAN
                <input type="text" id="sepa-iban" name="payment[cko-sepa-iban]" validate-one-required-by-name class="sepa-iban required-entry"/>
            </label>
        </div>
        <div>
            <label for="sepa-bic" >BIC
                <input type="text" id="sepa-bic" name="payment[cko-sepa-bic]"/>
            </label>
        </div>
    </div>

    <script type="text/javascript">

        var route = "<?php echo Mage::app()->getRequest()->getRouteName(); ?>";

        // only show Checkout Apms when the method is selected
        var apmSelector = document.getElementById('p_method_checkoutcomapms');
        var apmForm = document.getElementById('cko-apm-container');
        apmSelector.addEventListener('click', function () {
            apmForm.style.display = apmSelector.checked ? '' : 'none';
        });

        jQuery("input:radio.cko-apms").change(function(){
            if (jQuery('#cko-apms-boleto').length > 0 && jQuery("input:radio.cko-apms:checked").val() == 'boleto') {
                // Show boleto form
                jQuery('.boleto-info').show();
                jQuery('.ideal-bank-info').hide();
                jQuery('.giropay-bank-info').hide();
                jQuery('.klarna-details').hide();
                jQuery('.sepa-info').hide();

            } else if(jQuery('#cko-apms-ideal').length > 0 && jQuery("input:radio.cko-apms:checked").val() == 'ideal') {
                // Show Ideal form
                jQuery('.ideal-bank-info').show();
                jQuery('.boleto-info').hide();
                jQuery('.giropay-bank-info').hide();
                jQuery('.klarna-details').hide();
                jQuery('.sepa-info').hide();

            } else if(jQuery('#cko-apms-giropay').length > 0 && jQuery("input:radio.cko-apms:checked").val() == 'giropay') {
                // Show Giropay form
                jQuery('.giropay-bank-info').show();
                jQuery('.ideal-bank-info').hide();
                jQuery('.boleto-info').hide();
                jQuery('.klarna-details').hide();
                jQuery('.sepa-info').hide();

            } else if(jQuery('#cko-apms-klarna').length > 0 && jQuery("input:radio.cko-apms:checked").val() == 'klarna') {
                // initialise klarna session
                window.klarnaAsyncCallback();

                // Show klarna details
                jQuery('.klarna-details').show();
                jQuery('.giropay-bank-info').hide();
                jQuery('.ideal-bank-info').hide();
                jQuery('.boleto-info').hide();
                jQuery('.sepa-info').hide();

            } else if(jQuery('#cko-apms-sepa').length > 0 && jQuery("input:radio.cko-apms:checked").val() == 'sepa') {
                // Show Giropay form
                jQuery('.sepa-info').show();
                jQuery('.giropay-bank-info').hide();
                jQuery('.ideal-bank-info').hide();
                jQuery('.boleto-info').hide();
                jQuery('.klarna-details').hide();

            } else {
                jQuery('.boleto-info').hide();
                jQuery('.ideal-bank-info').hide();
                jQuery('.giropay-bank-info').hide();
                jQuery('.klarna-details').hide();
                jQuery('.sepa-info').hide();
            }
        })

    </script>

</div>